# .cmake-format
format:
  line_width: 120
  tab_size: 2
  separate_ctrl_name_with_space: false
  separate_fn_name_with_space: false
  dangle_parens: false
  max_pargs_hwrap: 3
  line_ending: unix
  bullet_char: '*'
  enum_char: '.'

additional_commands:
  foo:
    flags:
      - BAR
      - BAZ
    kwargs:
      DEPENDS: '*'
      HEADERS: '*'
      SOURCES: '*'

markup:
  enable_markup: false
