name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "Windows MSVC"
            os: windows-latest
            triplet: x64-windows
            vcpkg_dir: C:/vcpkg

          - name: "Ubuntu GCC"
            os: ubuntu-latest
            triplet: x64-linux
            vcpkg_dir: /usr/local/share/vcpkg

          - name: "macOS Clang"
            os: macos-latest
            triplet: x64-osx
            vcpkg_dir: /usr/local/share/vcpkg

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'latest'

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libgl1-mesa-dev

      - name: Configure CMake
        run: |
          cmake -B build \
            -DCMAKE_TOOLCHAIN_FILE=${{ matrix.config.vcpkg_dir }}/scripts/buildsystems/vcpkg.cmake \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Build examples
        run: cmake --build build --config Release --target minimal_example
